/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type BpmnFile struct {

	Type_ string `json:"type"`

	Attributes BpmnFileAttributes `json:"attributes,omitempty"`
}
