/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type FlowAttributes struct {

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	ProcessId string `json:"process_id"`

	FromObjectId string `json:"from_object_id"`

	FromObjectType string `json:"from_object_type"`

	ToObjectId string `json:"to_object_id"`

	ToObjectType string `json:"to_object_type"`

	Type_ string `json:"type"`

	Condition string `json:"condition,omitempty"`

	Default_ bool `json:"default"`

	Optional bool `json:"optional"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
