/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type GatewayAttributes struct {

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	ProcessId string `json:"process_id"`

	Type_ string `json:"type"`

	Direction string `json:"direction,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
