/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

// JSON API Response with collection of Items in array
type GatewayCollection struct {

	Data []Gateway `json:"data,omitempty"`

	Meta Meta `json:"meta,omitempty"`
}
