/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type GroupAttributes struct {

	Code string `json:"code"`

	Title string `json:"title"`

	Description string `json:"description,omitempty"`

	Status string `json:"status,omitempty"`

	// User IDs array
	Users []string `json:"users,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
