/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

// JSON API response with a collection of the input/outputs in the array
type InputOutputCollection struct {

	Data []InputOutput `json:"data,omitempty"`

	Meta Meta `json:"meta,omitempty"`
}
