/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type InstanceAttributes struct {

	ProcessId string `json:"process_id"`

	ParentInstanceId string `json:"parent_instance_id,omitempty"`

	InitUserId string `json:"init_user_id,omitempty"`

	Pin string `json:"pin,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	Status string `json:"status"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
