/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type ModelError struct {

	Code string `json:"code"`

	Title string `json:"title,omitempty"`

	Detail string `json:"detail,omitempty"`

	Message string `json:"message,omitempty"`
}
