/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type PaginationLinks struct {

	Next string `json:"next,omitempty"`

	Previous string `json:"previous,omitempty"`
}
