/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type ProcessCollection1 struct {

	Data []Process `json:"data"`

	Meta MetaLog `json:"meta,omitempty"`
}
