/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type ProcessAttributes struct {

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	ParentProcessId string `json:"parent_process_id,omitempty"`

	Status string `json:"status"`

	DurationBy string `json:"duration_by"`

	Type_ string `json:"type"`

	Assignment bool `json:"assignment,omitempty"`

	DesignAccess string `json:"design_access"`

	ShowMap bool `json:"show_map,omitempty"`

	ShowMessage bool `json:"show_message,omitempty"`

	ShowDelegate bool `json:"show_delegate,omitempty"`

	ShowDynaform bool `json:"show_dynaform,omitempty"`

	CategoryId string `json:"category_id,omitempty"`

	SubCategoryId string `json:"sub_category_id,omitempty"`

	CreateUserId string `json:"create_user_id,omitempty"`

	Debug bool `json:"debug,omitempty"`

	DynaformSummaryId string `json:"dynaform_summary_id,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
