/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type TaskAttributes struct {

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	ProcessId string `json:"process_id"`

	Type_ string `json:"type"`

	AssignType string `json:"assign_type"`

	PriorityVariable string `json:"priority_variable,omitempty"`

	AssignVariable string `json:"assign_variable,omitempty"`

	GroupVariable string `json:"group_variable,omitempty"`

	MiInstanceVariable string `json:"mi_instance_variable,omitempty"`

	MiCompleteVariable string `json:"mi_complete_variable,omitempty"`

	TransferFly bool `json:"transfer_fly"`

	CanUpload bool `json:"can_upload"`

	ViewUpload bool `json:"view_upload"`

	ViewAdditionalDocumentation bool `json:"view_additional_documentation"`

	Start bool `json:"start"`

	SendLastEmail bool `json:"send_last_email"`

	DerivationScreenTpl string `json:"derivation_screen_tpl,omitempty"`

	SelfserviceTimeout int32 `json:"selfservice_timeout"`

	SelfserviceTime string `json:"selfservice_time,omitempty"`

	SelfserviceTimeUnit string `json:"selfservice_time_unit,omitempty"`

	SelfserviceExecution string `json:"selfservice_execution,omitempty"`

	LastAssignedUserId string `json:"last_assigned_user_id,omitempty"`

	Script string `json:"script,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
