/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type TaskInstanceAttributes struct {

	TaskId string `json:"task_id"`

	InstanceId string `json:"instance_id"`

	GroupId string `json:"group_id,omitempty"`

	UserId string `json:"user_id,omitempty"`

	Status string `json:"status"`

	Priority string `json:"priority"`

	DelegateDate string `json:"delegate_date,omitempty"`

	StartDate string `json:"start_date,omitempty"`

	FinishDate string `json:"finish_date,omitempty"`

	TaskDueDate string `json:"task_due_date,omitempty"`

	RiskDate string `json:"risk_date,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	InstanceOverduePercentage float64 `json:"instance_overdue_percentage,omitempty"`

	Data string `json:"data,omitempty"`

	Content string `json:"content,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
