/* 
 * example
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package pmio

type TokenAttributes struct {

	InstanceId string `json:"instance_id"`

	FlowId string `json:"flow_id,omitempty"`

	TokenKey string `json:"token_key,omitempty"`

	TokenCount int32 `json:"token_count,omitempty"`

	InitiatorObjectId string `json:"initiator_object_id,omitempty"`

	InitiatorObjectType string `json:"initiator_object_type,omitempty"`

	TargetObjectId string `json:"target_object_id,omitempty"`

	TargetObjectType string `json:"target_object_type,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
